# Generated by Django 2.2.4 on 2019-08-24 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nertz', '0002_game_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hand',
            old_name='user',
            new_name='player',
        ),
    ]
