# Generated by Django 2.2.4 on 2019-08-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nertz', '0003_auto_20190824_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='nertz',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hand',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
